repos:
  - repo: https://github.com/syntaqx/git-hooks
    rev: v0.0.17
    hooks:
    - id: shellcheck
    - id: shfmt
      args: 
        - "-l" # list files whose formatting differs from shfmt's
        - "-i 2" # indent: 0 for tabs (default), >0 for number of spaces
        - "-ci" # switch cases will be indented
        - "-w" # write result to file instead of stdout
  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.9
    hooks:
    - id: mdformat
      additional_dependencies:
      - mdformat-gfm # GitHub Flavored Markdown support
  - repo: https://codeberg.org/frnmst/md-toc
    rev: 8.0.1  # or a specific git tag from md-toc
    hooks:
    - id: md-toc
      args:
        - "--in-place"
        - "github"
        - "--header-levels 6"